apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: node-hostname
        image: {{ .Values.image.name }}:{{ .Values.image.version }}
        imagePullPolicy: Never
        ports:
        - containerPort: 3{{ .Values.deployment.port }}