apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  ports:
  - port: {{ .Values.deployment.port }}
    protocol: TCP
  selector:
    app: {{ .Values.deployment.name }}
  type: LoadBalancer